export const RETRIEVE_USERS = "RETRIEVE_USERS";
export const RETRIEVE_USER = "RETRIEVE_USER";
export const UPDATE_USER = "UPDATE_USER";
export const RETRIEVE_USERS_BY_TITLE = "RETRIEVE_USERS_BY_TITLE";

export const RETRIEVE_POSTS = "RETRIEVE_POSTS";
export const RETRIEVE_POST = "RETRIEVE_POST";
export const RETRIEVE_POSTS_BY_USERID = "RETRIEVE_POSTS_BY_USERID";